name: My First Workflow
on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Welcome Message
          run:  echo "My first Github Action Command" 
          
        - name: List Files
          run: ls

        - name: Read File
          run: cat README.md || echo "README.md file is not found"